### QUESTION 1

In [1]:
# a)
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.to_csv("titanic.csv", index=False)
print("DataSet Saved Successfully")

# creating the dictionary
import csv

records = []
with open("titanic.csv", "r") as f:
    reader = csv.DictReader(f)

    for row in reader:
        records.append(row)
        
# b)
print("\n First three records")
for record in records[:3]:
    print(record)

print("\nTotal Number of Passengers:", len(records))

# c)
sex_set = set()

for record in records:
    sex_set.add(record["Sex"])

print("\nUnique Values in Sex Column:")
print(sex_set)

#d 
class_count = {}

for record in records:
    pclass = record["Pclass"]

    if pclass in class_count:
        class_count[pclass] += 1
    else:
        class_count[pclass] = 1

print("\nPassengers in Each Class:")
print(class_count)

# e)
survivors = []

for record in records:
    if record["Survived"] == "1":
        survivors.append(record)

with open("survivors.csv", "w", newline="") as file:
    writer = csv.DictWriter(file, fieldnames=records[0].keys())

    writer.writeheader()
    writer.writerows(survivors)

print("\nNumber of survivor records written:", len(survivors))

DataSet Saved Successfully

 First three records
{'PassengerId': '1', 'Survived': '0', 'Pclass': '3', 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': '22.0', 'SibSp': '1', 'Parch': '0', 'Ticket': 'A/5 21171', 'Fare': '7.25', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '2', 'Survived': '1', 'Pclass': '1', 'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Sex': 'female', 'Age': '38.0', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17599', 'Fare': '71.2833', 'Cabin': 'C85', 'Embarked': 'C'}
{'PassengerId': '3', 'Survived': '1', 'Pclass': '3', 'Name': 'Heikkinen, Miss. Laina', 'Sex': 'female', 'Age': '26.0', 'SibSp': '0', 'Parch': '0', 'Ticket': 'STON/O2. 3101282', 'Fare': '7.925', 'Cabin': '', 'Embarked': 'S'}

Total Number of Passengers: 891

Unique Values in Sex Column:
{'female', 'male'}

Passengers in Each Class:
{'3': 491, '1': 216, '2': 184}

Number of survivor records written: 342

### QUESTION 2

In [2]:
import pandas as pd 
import numpy as np

#load the dataset
df = pd.read_csv("titanic.csv")

# Remove rows with missing Age
df = df.dropna(subset=["Age"])

# Convert columns to NumPy arrays
age_arr = df["Age"].to_numpy()
fare_arr = df["Fare"].to_numpy()

# a)
print("Age Array")
print("Shape:", age_arr.shape)
print("Data Type:", age_arr.dtype)

print("\nFare Array")
print("Shape:", fare_arr.shape)
print("Data Type:", fare_arr.dtype)

# b) 
print("\nAge Statistics")
print(f"Mean: {np.mean(age_arr):.2f}")
print(f"Median: {np.median(age_arr):.2f}")
print(f"Standard Deviation: {np.std(age_arr):.2f}")

print("\nFare Statistics")
print(f"Mean: {np.mean(fare_arr):.2f}")
print(f"Median: {np.median(fare_arr):.2f}")
print(f"Standard Deviation: {np.std(fare_arr):.2f}")

# c)
young_passengers = age_arr[age_arr < 18]
print("\nPassengers younger than 18 years old: ", len(young_passengers))

Age Array
Shape: (714,)
Data Type: float64

Fare Array
Shape: (714,)
Data Type: float64

Age Statistics
Mean: 29.70
Median: 28.00
Standard Deviation: 14.52

Fare Statistics
Mean: 34.69
Median: 15.74
Standard Deviation: 52.88

Passengers younger than 18 years old:  113

### QUESTION 3

In [3]:
import pandas as pd

# Read the CSV file
data = pd.read_csv("titanic.csv")

# Store it as a DataFrame
df = pd.DataFrame(data)

# Display
df



# a)
print("Shape of the DataFrame:")
print(df.shape)

print("\nData Types of Each Column:")
print(df.dtypes)

print("\nFirst 5 Rows:")
display(pd.DataFrame(df.head()))

# b)
selected_df = pd.DataFrame(df[["Name", "Sex", "Age", "Pclass", "Survived"]])
print("Shape of Selected DataFrame:")
print(selected_df.shape)
display(selected_df)


# c)
highest_fare = df["Fare"].max()
highest_passenger = pd.DataFrame(df[df["Fare"] == highest_fare])
display(highest_passenger[["Name", "Pclass", "Fare"]])


# d)
first_class = pd.DataFrame(df[df["Pclass"] == 1])
print("First Class Passengers")
print("Shape:", first_class.shape)
display(first_class.head(3))

# Female Passengers Who Survived
female_survived = pd.DataFrame(
    df[(df["Sex"] == "female") & (df["Survived"] == 1)]
)
print("Female Passengers Who Survived")
print("Shape:", female_survived.shape)
display(female_survived.head(3))

# Passengers Older Than 60
older_than_60 = pd.DataFrame(df[df["Age"] > 60])

print("Passengers Older Than 60")
print("Shape:", older_than_60.shape)

display(older_than_60.head(3))

# e)
df["Family_Size"] = df["SibSp"] + df["Parch"] + 1
df["Is_Alone"] = df["Family_Size"] == 1
display(pd.DataFrame(df[["Family_Size", "Is_Alone"]].head()))

# f)
missing_values = df.isnull().sum()
missing_percentage = round((missing_values / len(df)) * 100, 2)
missing_df = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage (%)": missing_percentage
})
display(missing_df)

# g)
median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)
print("Median Age Used:", median_age)
display(pd.DataFrame(df.head()))

#h)
print("Embarked Value Counts Before Filling")
print(df["Embarked"].value_counts(dropna=False))
df["Embarked"] = df["Embarked"].fillna("S")
print("\nEmbarked Value Counts After Filling")
print(df["Embarked"].value_counts(dropna=False))
display(pd.DataFrame(df.head()))

# i)
print("Columns before Removing cabins")
print(df.columns)
df = df.drop(columns=["Cabin"])
print("\nColumns after removing cabins")
print(df.columns)
display(pd.DataFrame(df.head()))

Shape of the DataFrame:
(891, 12)

Data Types of Each Column:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

First 5 Rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Shape of Selected DataFrame:
(891, 5)

,Name,Sex,Age,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1
2,"Heikkinen, Miss. Laina",female,26.0,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,1
4,"Allen, Mr. William Henry",male,35.0,3,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,2,0
887,"Graham, Miss. Margaret Edith",female,19.0,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,3,0
889,"Behr, Mr. Karl Howell",male,26.0,1,1
890,"Dooley, Mr. Patrick",male,32.0,3,0

                                   Name  Pclass      Fare
258                    Ward, Miss. Anna       1  512.3292
679  Cardeza, Mr. Thomas Drake Martinez       1  512.3292
737              Lesurer, Mr. Gustave J       1  512.3292

First Class Passengers
Shape: (216, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

Female Passengers Who Survived
Shape: (233, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

Passengers Older Than 60
Shape: (22, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C

   Family_Size  Is_Alone
0            2     False
1            2     False
2            1      True
3            2     False
4            1      True

             Missing Values  Percentage (%)
PassengerId               0            0.00
Survived                  0            0.00
Pclass                    0            0.00
Name                      0            0.00
Sex                       0            0.00
Age                     177           19.87
SibSp                     0            0.00
Parch                     0            0.00
Ticket                    0            0.00
Fare                      0            0.00
Cabin                   687           77.10
Embarked                  2            0.22
Family_Size               0            0.00
Is_Alone                  0            0.00

Median Age Used: 28.0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Is_Alone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,True

Embarked Value Counts Before Filling
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

Embarked Value Counts After Filling
Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Is_Alone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,True

Columns before Removing cabins
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Family_Size',
       'Is_Alone'],
      dtype='object')

Columns after removing cabins
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'Family_Size', 'Is_Alone'],
      dtype='object')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_Size,Is_Alone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,2,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,2,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,1,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,2,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1,True